[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableStaticServing = true
runOnSave = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = false
